
name: Linux, build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build configuration"
        required: true
        default: "Release"

env:
  BUILD_TYPE: Release
  BUILD_DIRECTORY: build
  APP_NAME: market-bridge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update  
        sudo apt-get install -y libssl-dev

    - name: Configure CMake
      run: cmake -S. -B ${{github.workspace}}/${{env.BUILD_DIRECTORY}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIRECTORY}} --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/${{env.BUILD_DIRECTORY}}/tests
      run: ctest -V

    - name: Run ${{env.APP_NAME}}
      working-directory: ${{github.workspace}}/${{env.BUILD_DIRECTORY}}
      run: ./${{env.APP_NAME}} --help
      
